### ISSUE TITLE
Issue with remote cache config

### ISSUE THREAD

**Issue by aaylward** [bazel-contrib/setup-bazel#44]
Hello 👋 

Thanks for making this action! It's super helpful!

I was just trying to configure google-credentials to use a GCP remote cache, but I'm running into an EACCES error when the action tries to make a temporary directory for the credentials file:

```
Error: EACCES: permission denied, mkdtemp '/tmpXXXXXX'
    at Object.mkdtempSync (node:fs:2971:18)
    at Object.700 (/home/runner/work/_actions/bazel-contrib/setup-bazel/0.9.0/dist/config.js:67:1)
    at __nccwpck_require__ (/home/runner/work/_actions/bazel-contrib/setup-bazel/0.9.0/dist/webpack/bootstrap:21:1)
    at /home/runner/work/_actions/bazel-contrib/setup-bazel/0.9.0/dist/index.js:8:1
    at Object.<anonymous> (/home/runner/work/_actions/bazel-contrib/setup-bazel/0.9.0/dist/main/index.js:97137:12)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
```

Which appears to be happening here: https://github.com/bazel-contrib/setup-bazel/blob/main/config.js#L67 

Am I missing some configuration that would make this work?

Thanks in advance!

**Comment by aaylward** [comment]
This old open issue seems potentially related: https://github.com/actions/toolkit/issues/518

**Comment by aaylward** [comment]
It looks like the tmp dir creation can be done in the RUNNER_TEMP like:
```
  const tmpDir = core.toPosixPath(fs.mkdtempSync(process.env.RUNNER_TEMP))
```

**Comment by p0deje** [comment]
`google-credentials` is a configuration that Selenium project ended up not using, so I am not surprised it's broken to be honest, I probably should have removed it at all.

Are you up to send a PR with a fix for this?

**Comment by aaylward** [comment]
np -- https://github.com/bazel-contrib/setup-bazel/pull/47

**Comment by aaylward** [comment]
@p0deje I'll leave this open until 0.9.1 is released

**Comment by p0deje** [comment]
Just released

**Comment by aaylward** [comment]
Thanks @p0deje

**Comment by p0deje** [comment]
thanks for fix @aaylward
